### ISSUE TITLE
Adding authentication to web-socket connection

### ISSUE THREAD

**Issue by m-rit** [Nicolas-ggd/go-notification#10]
@Nicolas-ggd, I noticed you mentioned  in your TODO-list that authentication component for web-sockets is not implemented yet.
Can I add an enhancement for the authentication component ?

**Comment by Nicolas-ggd** [comment]
> @Nicolas-ggd, I noticed you mentioned in your TODO-list that authentication component for web-sockets is not implemented yet. Can I add an enhancement for the authentication component ?

Yeah, for sure

**Comment by Nicolas-ggd** [comment]
> @Nicolas-ggd, I noticed you mentioned in your TODO-list that authentication component for web-sockets is not implemented yet. Can I add an enhancement for the authentication component ?

Did you have permission to create new branch?

**Comment by m-rit** [comment]
yeah, I have forked this repo
